export type CandidateType = "맞춤법" | "띄어쓰기" | "표준어" | "외래어";
export type CandidateStatus = "ready" | "contextual" | "needs-review";

export interface ReverseRuleCandidate {
  id: string;
  correct: string;
  wrong: string;
  type: CandidateType;
  status: CandidateStatus;
  contextRequired: boolean;
  reason: string;
  example: string;
  sourceTitle: string;
  sourceUrl: string;
  notes?: string;
}

export const reverseRuleCandidates: ReverseRuleCandidate[] = [
  {
    id: "spelling-myeochil",
    correct: "며칠",
    wrong: "몇일",
    type: "맞춤법",
    status: "ready",
    contextRequired: false,
    reason: "'며칠'은 '몇 일'이 아니라 한 단어로 굳어진 표기입니다.",
    example: "며칠 전부터 기다렸어요.",
    sourceTitle: "국립국어원 온라인가나다: 며칠, 몇 일 구분",
    sourceUrl: "https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=27&pageIndex=1&qna_seq=328160",
  },
  {
    id: "spacing-yo-myeochil",
    correct: "요 며칠",
    wrong: "요며칠",
    type: "띄어쓰기",
    status: "ready",
    contextRequired: false,
    reason: "'요'는 뒤 체언과 띄어 쓰고, '며칠'은 '몇일'로 적지 않습니다.",
    example: "요 며칠 날씨가 좋았어요.",
    sourceTitle: "국립국어원 온라인가나다: 요몇일과 요며칠",
    sourceUrl: "https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&pageIndex=1&qna_seq=327456",
  },
  {
    id: "spelling-dwaeyo",
    correct: "돼요",
    wrong: "되요",
    type: "맞춤법",
    status: "ready",
    contextRequired: false,
    reason: "'돼요'는 '되어요'가 줄어든 말입니다.",
    example: "이제 가도 돼요.",
    sourceTitle: "국립국어원 상담 사례: 돼요",
    sourceUrl: "https://www.korean.go.kr/front/mcfaq/mcfaqView.do?mcfaq_seq=6761",
  },
  {
    id: "spelling-dwaesseo",
    correct: "됐",
    wrong: "됬",
    type: "맞춤법",
    status: "ready",
    contextRequired: false,
    reason: "'됐'은 '되었'의 준말이고, '됬'은 표준 표기가 아닙니다.",
    example: "준비가 다 됐어요.",
    sourceTitle: "국립국어원 온라인가나다: 되요/돼요",
    sourceUrl: "https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&pageIndex=1&qna_seq=306151",
  },
  {
    id: "spelling-wenmanhamyeon",
    correct: "웬만하면",
    wrong: "왠만하면",
    type: "맞춤법",
    status: "ready",
    contextRequired: false,
    reason: "'왠지'를 제외한 대부분의 경우에는 '웬'을 씁니다.",
    example: "웬만하면 오늘 끝내요.",
    sourceTitle: "국립국어원 온라인가나다: 웬/왠 맞춤법",
    sourceUrl: "https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&pageIndex=1&qna_seq=326371",
  },
  {
    id: "spelling-wenil",
    correct: "웬일",
    wrong: "왠일",
    type: "맞춤법",
    status: "ready",
    contextRequired: false,
    reason: "'웬일'은 하나의 단어로 등재된 표기입니다.",
    example: "오늘은 웬일로 일찍 왔어요?",
    sourceTitle: "국립국어원 온라인가나다: 웬/왠 맞춤법",
    sourceUrl: "https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&pageIndex=1&qna_seq=326371",
  },
  {
    id: "spelling-waenji",
    correct: "왠지",
    wrong: "웬지",
    type: "맞춤법",
    status: "ready",
    contextRequired: false,
    reason: "'왠지'는 '왜인지'가 줄어든 말입니다.",
    example: "왠지 오늘은 기분이 좋아요.",
    sourceTitle: "국립국어원 온라인가나다: 왠/웬 차이",
    sourceUrl: "https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=&pageIndex=1&qna_seq=311176",
  },
  {
    id: "spelling-geumse",
    correct: "금세",
    wrong: "금새",
    type: "맞춤법",
    status: "ready",
    contextRequired: false,
    reason: "'지금 바로'의 뜻은 '금세'로 적습니다.",
    example: "비가 그치더니 금세 맑아졌어요.",
    sourceTitle: "국립국어원 소식지: 금새와 금세",
    sourceUrl: "https://www.korean.go.kr/nkview/news_pdf/2023_9%282%29.pdf",
  },
  {
    id: "standard-seollem",
    correct: "설렘",
    wrong: "설레임",
    type: "표준어",
    status: "ready",
    contextRequired: false,
    reason: "'설레다'에서 파생된 명사는 '설렘'입니다.",
    example: "새 일을 앞두고 설렘이 컸어요.",
    sourceTitle: "국립국어원 상담 사례: 설렘과 설레임",
    sourceUrl: "https://www.korean.go.kr/front/mcfaq/mcfaqView.do?mcfaq_seq=6031&mn_id=217",
  },
  {
    id: "standard-baram",
    correct: "바람",
    wrong: "바램",
    type: "표준어",
    status: "ready",
    contextRequired: false,
    reason: "소망의 뜻은 '바라다'에서 온 '바람'이 표준어입니다.",
    example: "내 바람은 네가 편히 지내는 거예요.",
    sourceTitle: "국립국어원 상담 사례: 바람, 바램",
    sourceUrl: "https://www.korean.go.kr/front/mcfaq/mcfaqView.do?mcfaq_seq=9128",
  },
  {
    id: "standard-barayo",
    correct: "바라요",
    wrong: "바래요",
    type: "표준어",
    status: "ready",
    contextRequired: false,
    reason: "소망을 나타내는 동사는 '바라다'이므로 '바라요'로 활용합니다.",
    example: "좋은 하루 보내길 바라요.",
    sourceTitle: "한국어 어문 규범: 표준어 규정 해설",
    sourceUrl: "https://www.korean.go.kr/front/page/pageView.do?page_id=P000088",
  },
  {
    id: "standard-baratda",
    correct: "바랐다",
    wrong: "바랬다",
    type: "표준어",
    status: "ready",
    contextRequired: false,
    reason: "'바라다'의 과거형은 '바랐다'입니다.",
    example: "좋은 결과가 있기를 바랐다.",
    sourceTitle: "한국어 어문 규범: 표준어 규정 해설",
    sourceUrl: "https://www.korean.go.kr/front/page/pageView.do?page_id=P000088",
  },
  {
    id: "spelling-eoi-eopda",
    correct: "어이없다",
    wrong: "어의없다",
    type: "맞춤법",
    status: "ready",
    contextRequired: false,
    reason: "'어이없다'는 '어이'가 포함된 말입니다.",
    example: "그 말은 정말 어이없다.",
    sourceTitle: "국립국어원 온라인가나다: 어이없다",
    sourceUrl: "https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&pageIndex=1&qna_seq=305402",
  },
  {
    id: "spelling-bandeusi",
    correct: "반드시",
    wrong: "반듯이",
    type: "맞춤법",
    status: "contextual",
    contextRequired: true,
    reason: "'꼭, 틀림없이'의 뜻이면 '반드시'를 씁니다.",
    example: "내일까지 반드시 제출하세요.",
    sourceTitle: "국립국어원 새국어소식: 반드시/반듯이",
    sourceUrl: "https://www.korean.go.kr/nkview/nknews/200510/87_3.html",
  },
  {
    id: "spelling-bandeusi-straight",
    correct: "반듯이",
    wrong: "반드시",
    type: "맞춤법",
    status: "contextual",
    contextRequired: true,
    reason: "'비뚤어지지 않고 바르게'의 뜻이면 '반듯이'를 씁니다.",
    example: "책을 반듯이 놓아 주세요.",
    sourceTitle: "국립국어원 새국어소식: 반드시/반듯이",
    sourceUrl: "https://www.korean.go.kr/nkview/nknews/200510/87_3.html",
  },
  {
    id: "spelling-matchida-answer",
    correct: "맞히다",
    wrong: "맞추다",
    type: "맞춤법",
    status: "contextual",
    contextRequired: true,
    reason: "정답을 알아내거나 과녁에 적중시키는 뜻이면 '맞히다'를 씁니다.",
    example: "문제의 답을 맞히다.",
    sourceTitle: "국립국어원 새국어소식: 맞히다와 맞추다",
    sourceUrl: "https://www.korean.go.kr/nkview/nknews/200507/84_3.html",
  },
  {
    id: "spelling-matchuda-compare",
    correct: "맞추다",
    wrong: "맞히다",
    type: "맞춤법",
    status: "contextual",
    contextRequired: true,
    reason: "비교하거나 기준에 맞게 하는 뜻이면 '맞추다'를 씁니다.",
    example: "친구와 답을 맞춰 보았다.",
    sourceTitle: "국립국어원 온라인가나다: 맞추다/맞히다",
    sourceUrl: "https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&pageIndex=1&qna_seq=314979",
  },
  {
    id: "spelling-buchida-stick",
    correct: "붙이다",
    wrong: "부치다",
    type: "맞춤법",
    status: "contextual",
    contextRequired: true,
    reason: "'붙다'와 관련된 뜻이면 '붙이다'를 씁니다.",
    example: "벽에 포스터를 붙이다.",
    sourceTitle: "국립국어원 상담 사례: 붙이다/부치다",
    sourceUrl: "https://www.korean.go.kr/front/mcfaq/mcfaqView.do?mcfaq_seq=9083",
  },
  {
    id: "spelling-buchida-send",
    correct: "부치다",
    wrong: "붙이다",
    type: "맞춤법",
    status: "contextual",
    contextRequired: true,
    reason: "편지를 보내거나 회의에 넘기는 뜻이면 '부치다'를 씁니다.",
    example: "편지를 부치다.",
    sourceTitle: "국립국어원 영상: 부치다와 붙이다",
    sourceUrl: "https://www.korean.go.kr/front/board/boardMovieView.do?b_movie_type=4&b_seq=334&board_id=14&mn_id=56&pageIndex=1",
  },
  {
    id: "particle-roseo",
    correct: "로서",
    wrong: "로써",
    type: "맞춤법",
    status: "contextual",
    contextRequired: true,
    reason: "지위, 신분, 자격을 나타내면 '로서'를 씁니다.",
    example: "친구로서 할 말이 있어요.",
    sourceTitle: "국립국어원 상담 사례: 로서, 로써",
    sourceUrl: "https://www.korean.go.kr/front/mcfaq/mcfaqView.do?mcfaq_seq=5568",
  },
  {
    id: "particle-rosseu",
    correct: "로써",
    wrong: "로서",
    type: "맞춤법",
    status: "contextual",
    contextRequired: true,
    reason: "수단, 도구, 재료, 시간의 기준을 나타내면 '로써'를 씁니다.",
    example: "대화로써 문제를 풀었다.",
    sourceTitle: "국립국어원 상담 사례: 로서, 로써",
    sourceUrl: "https://www.korean.go.kr/front/mcfaq/mcfaqView.do?mcfaq_seq=5568",
  },
  {
    id: "spelling-naatda-better",
    correct: "나음",
    wrong: "낫음",
    type: "맞춤법",
    status: "contextual",
    contextRequired: true,
    reason: "'더 좋다'의 뜻인 '낫다'도 명사형은 '나음'으로 씁니다.",
    example: "내가 하는 게 나음.",
    sourceTitle: "국립국어원 온라인가나다: 낫음/나음",
    sourceUrl: "https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=&pageIndex=1&qna_seq=320596",
  },
  {
    id: "spelling-nat-verb",
    correct: "나았습니다",
    wrong: "낫았습니다",
    type: "맞춤법",
    status: "ready",
    contextRequired: false,
    reason: "'낫다'는 모음 어미 앞에서 'ㅅ'이 탈락합니다.",
    example: "감기가 나았습니다.",
    sourceTitle: "국립국어원 온라인가나다: 낫다 활용",
    sourceUrl: "https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&pageIndex=1&qna_seq=305076",
  },
  {
    id: "spelling-gareuchida",
    correct: "가르치다",
    wrong: "가리키다",
    type: "맞춤법",
    status: "contextual",
    contextRequired: true,
    reason: "지식이나 기술을 익히게 하는 뜻이면 '가르치다'를 씁니다.",
    example: "학생에게 수학을 가르치다.",
    sourceTitle: "국립국어원 온라인가나다: 가르키다",
    sourceUrl: "https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=261&pageIndex=1&qna_seq=325076",
  },
  {
    id: "spelling-garikida",
    correct: "가리키다",
    wrong: "가르치다",
    type: "맞춤법",
    status: "contextual",
    contextRequired: true,
    reason: "손가락 등으로 방향이나 대상을 집어 보이는 뜻이면 '가리키다'를 씁니다.",
    example: "손가락으로 길을 가리키다.",
    sourceTitle: "국립국어원 온라인가나다: 가르키다",
    sourceUrl: "https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=261&pageIndex=1&qna_seq=325076",
  },
  {
    id: "spacing-hal-su",
    correct: "할 수",
    wrong: "할수",
    type: "띄어쓰기",
    status: "ready",
    contextRequired: false,
    reason: "의존 명사 '수'는 앞말과 띄어 씁니다.",
    example: "오늘 안에 할 수 있어요.",
    sourceTitle: "한국어 어문 규범: 한글 맞춤법 제5장 띄어쓰기",
    sourceUrl: "https://www.korean.go.kr/kornorms/m/m_main.do",
  },
  {
    id: "spacing-geot-gatda",
    correct: "것 같다",
    wrong: "것같다",
    type: "띄어쓰기",
    status: "ready",
    contextRequired: false,
    reason: "'것'은 의존 명사이므로 앞뒤 표현과 띄어 쓰는 것이 원칙입니다.",
    example: "비가 올 것 같다.",
    sourceTitle: "한국어 어문 규범: 한글 맞춤법 제5장 띄어쓰기",
    sourceUrl: "https://www.korean.go.kr/kornorms/m/m_main.do",
  },
  {
    id: "spacing-on-ji",
    correct: "온 지",
    wrong: "온지",
    type: "띄어쓰기",
    status: "ready",
    contextRequired: false,
    reason: "시간의 경과를 나타내는 의존 명사 '지'는 띄어 씁니다.",
    example: "집에 온 지 한 시간이 지났어요.",
    sourceTitle: "한국어 어문 규범: 한글 맞춤법 제5장 띄어쓰기",
    sourceUrl: "https://www.korean.go.kr/kornorms/m/m_main.do",
  },
  {
    id: "spacing-subakke",
    correct: "수밖에",
    wrong: "수 밖에",
    type: "띄어쓰기",
    status: "ready",
    contextRequired: false,
    reason: "'수밖에'는 하나의 조사처럼 굳어 붙여 씁니다.",
    example: "기다릴 수밖에 없어요.",
    sourceTitle: "한국어 어문 규범: 한글 맞춤법 제5장 띄어쓰기",
    sourceUrl: "https://www.korean.go.kr/kornorms/m/m_main.do",
  },
  {
    id: "spacing-ppunman-anira",
    correct: "뿐만 아니라",
    wrong: "뿐만아니라",
    type: "띄어쓰기",
    status: "ready",
    contextRequired: false,
    reason: "'뿐만 아니라'는 각 단위를 띄어 씁니다.",
    example: "빠를 뿐만 아니라 정확해요.",
    sourceTitle: "한국어 어문 규범: 한글 맞춤법 제5장 띄어쓰기",
    sourceUrl: "https://www.korean.go.kr/kornorms/m/m_main.do",
  },
  {
    id: "loanword-aekseseori",
    correct: "액세서리",
    wrong: "악세사리",
    type: "외래어",
    status: "ready",
    contextRequired: false,
    reason: "accessory의 규범 표기는 '액세서리'입니다.",
    example: "작은 액세서리를 하나 샀어요.",
    sourceTitle: "국립국어원 조사 자료: 외래어 표기법 문항",
    sourceUrl:
      "https://www.korean.go.kr/common/download.do?c_file_name=a49e6920-71d6-4ade-81a9-33b85f3c3798.pdf&file_path=reportData&o_file_name=KR100012711.pdf",
  },
  {
    id: "loanword-kontencheu",
    correct: "콘텐츠",
    wrong: "컨텐츠",
    type: "외래어",
    status: "ready",
    contextRequired: false,
    reason: "contents의 규범 표기는 '콘텐츠'입니다.",
    example: "새 콘텐츠를 준비하고 있어요.",
    sourceTitle: "국립국어원 바른 국어 생활: 콘텐츠/컨텐츠",
    sourceUrl:
      "https://www.korean.go.kr/common/download.do?c_file_name=e05deaf1-1f57-4ed9-b8a2-ea6df1a06910_0.pdf&file_path=etcData&o_file_name=%EB%B0%94%EB%A5%B8+%EA%B5%AD%EC%96%B4+%EC%83%9D%ED%99%9C+%28%EA%B5%90%EC%82%AC+%EC%A7%81%EB%AC%B4+%EC%97%B0%EC%88%98+%EA%B5%90%EC%9E%AC%29.pdf",
  },
  {
    id: "loanword-mesiji",
    correct: "메시지",
    wrong: "메세지",
    type: "외래어",
    status: "ready",
    contextRequired: false,
    reason: "message의 규범 표기는 '메시지'입니다.",
    example: "짧은 메시지를 보냈어요.",
    sourceTitle: "국립국어원 조사 자료: 외래어 표기법 문항",
    sourceUrl:
      "https://www.korean.go.kr/common/download.do?c_file_name=a49e6920-71d6-4ade-81a9-33b85f3c3798.pdf&file_path=reportData&o_file_name=KR100012711.pdf",
  },
  {
    id: "loanword-keikeu",
    correct: "케이크",
    wrong: "케익",
    type: "외래어",
    status: "ready",
    contextRequired: false,
    reason: "cake의 규범 표기는 '케이크'입니다.",
    example: "생일 케이크를 준비했어요.",
    sourceTitle: "국립국어원 온라인가나다: 케이크와 케익",
    sourceUrl: "https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=321881",
  },
  {
    id: "loanword-keopisyop",
    correct: "커피숍",
    wrong: "커피샵",
    type: "외래어",
    status: "ready",
    contextRequired: false,
    reason: "coffee shop의 규범 표기는 '커피숍'입니다.",
    example: "근처 커피숍에서 만나요.",
    sourceTitle: "국립국어원 바른 국어 생활: 외래어 표기법",
    sourceUrl:
      "https://www.korean.go.kr/common/download.do?c_file_name=fa64499d-d020-44e9-895c-6116a37a58e4_0.pdf&file_path=etcData&o_file_name=%EB%B0%94%EB%A5%B8+%EA%B5%AD%EC%96%B4+%EC%83%9D%ED%99%9C+-+%EA%B5%AD%EC%96%B4%EB%AC%B8%ED%99%94%ED%95%99%EA%B5%90.pdf",
  },
];

export function getAttachableReverseRuleCandidates(options: { includeContextual?: boolean } = {}) {
  return reverseRuleCandidates.filter((candidate) => {
    if (candidate.status === "needs-review") return false;
    if (candidate.status === "contextual" && !options.includeContextual) return false;
    return true;
  });
}
